### ISSUE TITLE
AWS.config.credentials.identityId is null + s3 doesn't allow https directly

### ISSUE THREAD

**Issue by trevor-h** [awslabs/samljs-serverless-sample#3]
Hello,

Following the blog post at https://aws.amazon.com/blogs/compute/saml-for-your-serverless-javascript-application-part-i/ led me to this repo. I'm following the sample1 config and everything is working except for the client side Javascript interacting with Cognito.

The variable identityId is null when the request for AWS.config.credentials.get fails with a 400 error at https://github.com/awslabs/samljs-serverless-sample/blob/master/Scenario1/website/index.html#L42

There is no output in the 400 response but there is the following headers:
x-amzn-ErrorMessage:Unauthenticated access is not supported for this identity pool.
x-amzn-ErrorType:NotAuthorizedException:
x-amzn-RequestId:47918b77-1643-11e7-b427-85931b95b74f

It's very possible I've missed something but something seems off. Getting the identityId fails because of unauthenticated access and it's needed in getSamlCredentials. Possible client sdk version issue?

Also I noted in the tutorial reference is made to hosting the static site directly from S3 and Cloudfront as an option. It seems that https is not supported for static sites any longer (I seem to remember it was possible..)

Thanks!
TH

**Comment by trevor-h** [comment]
I just wanted to comment that something seems to have been wrong when the identity pool was created as  I recreated it and no longer got the 400 error.

I'll leave this issue as a reference for anyone else whom might see this problem as it had me scratching my head a bit.

**Comment by undefobj** [comment]
Hi Trevor, when creating an Identity Pool you need to enable Unauthenticated Access in the Cognito Wizard. Most likely this option was unchecked when you first created the pool. For more information see the documentation on this Cognito feature: http://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html
