### ISSUE TITLE
Service Provider Initiated Login

### ISSUE THREAD

**Issue by RebelSyntax** [awslabs/samljs-serverless-sample#5]
Hi,

It appears that both of these examples are Identity Provider Initiated Logins.  Is it possible to adapt this solution to Service Provider Initiated Logins?  

Thanks!

**Comment by undefobj** [comment]
Hello - The sample is designed to be generic enough to customize the logic for SP initiated and partially does this already. If you look at the JavaScript in the index.html file you should see a `loginWorkflow` method and `activelogin` variable:

`
function loginWorkflow(){
    var activelogin = sessionStorage.getItem('activelogin');
`

The sample by default just calls this method on startup and redirects as appropriate based on the state of this variable. For SP initiated flow you could perform similar logic when you try to access a protected resource on the SP domain.
