### ISSUE TITLE
how to update identity id when a new identity id is created for an existing parent identity?

### ISSUE THREAD

**Issue by sdole** [awslabs/samljs-serverless-sample#7]
We have a serverless app using almost identical code as in this GitHub. It works very well.

Question is: when a user clears cache or logs in from a new device, this code creates a new "anonymous" identity id upon first access. Then, in the getCredentialsForIdentity call, cognito returns credentials along with the first identity id for that SAML assertion. How do we ensure that the AWS JSSDK switches over to the new identity id? 

I ask this because, in the developer console, I don't see the identity id being updated in the AWS.config.credentials object. Nor do I see it being updated in localStorage on the key aws.cognito.identity-id.us-east-1:<pool id>

The problem is that we end up having many identity ids for which we don't know what the parent is. Is there a way to find which parent id does an identity id belong to?

**Comment by undefobj** [comment]
Not really sure, this would be a better question for the JavaScript SDK team on updating the credentials object (https://github.com/aws/aws-sdk-js)

**Comment by sdole** [comment]
Thanks! We ended up asking AWS premium support. They have suggested not to create a new identity (as done in [line 34](https://github.com/awslabs/samljs-serverless-sample/blob/c63cbdb8b32d0da1cf4f8faeb4686985b3013ed0/Scenario1/website/index.html#L34). Instead use JSSDK's AWS.CognitoIdentityCredentials.getId() method with the SAML assertion to obtain the unique identity associated with that SAML assertion (or a new one if none exists).

The expressly suggested that they will reach out to the authors of the [aws blog post](https://aws.amazon.com/blogs/compute/saml-for-your-serverless-javascript-application-part-i/) to possibly correct it.
